spring:
  application:
    name: stockmaintenance-service
    
server:
  port: 8006
  
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8005/eureka
  instance:
    hostname: Phani
  
